### ISSUE TITLE
Input element is not cleared on focus

### ISSUE THREAD

**Issue by JustRonald** [aguirrel/ng-currency#100]
This directive works great and shows "€ 0.00" but when I click on the input field it changes to "0.00". I cannot find a way to clear the input field or to set focus on the first zero in the input field when I set focus to the textbox. Am I missing something or is this not a feature yet? If not, any ideas how to fix this?

**Comment by nick-woodward** [comment]
Not entirely sure what's actually happening vs what you expected to happen. 
Can you post an example using this jsbin?
https://jsbin.com/tuhujupeye/edit?html,output

Thanks,
Nick

**Comment by JustRonald** [comment]
Maybe it's better to show you with screenshots:

No focus:
![nofocus](https://cloud.githubusercontent.com/assets/17311200/17403040/594bb9d6-5a56-11e6-95cd-f74dbfb1f89f.PNG)

With focus:
![withfocus](https://cloud.githubusercontent.com/assets/17311200/17403041/5ceb813e-5a56-11e6-8c03-4026c741bc1e.PNG)

I'm trying to get the first zero selected when I set focus on the input field OR to clear the input field (remove the placeholder) when I set focus.

**Comment by aguirrel** [comment]
Hi @JustRonald,

From version 0.9.x, "focusing on an input will show the model value rather then the formatted value".  I know that 0.00 seems as a special case but this is the expected behavior.

Anyway I think you could use ng-currency AND select all text when model is 0.  From this http://stackoverflow.com/questions/14995884/select-text-on-input-focus I did a plunkr with this example:

http://plnkr.co/edit/k2po9j9tIxPSaUJwyzW9?p=preview

Perhaps it helps.

@nick-woodward what do you think about adding this "select all" as an option for ng-currency?

Example: http://plnkr.co/edit/Al6ngqmryCXxOxYjulGI?p=preview

Best regards.

**Comment by nick-woodward** [comment]
I'm not opposed to the idea, however I feel like this functionality could be more useful as a separate directive.

https://jsbin.com/yobifedojo/edit?html,output

Even though this works in this scenario, it breaks in every scenario where the formatted value is different then the real value.

https://jsbin.com/jikawixaje/edit?html,output 

**We really have a couple of options:**
1. We add this as native functionality
2. We find a way to fix it so that external directives are notified of our changes to the value

**Comment by aguirrel** [comment]
Hi @nick-woodward ! I agree, this should be another directive to not add complex to this directive ;)

@JustRonald are you ok with this suggestion? Or you see it doesn't work for you?

**Comment by JustRonald** [comment]
This is a great solution, works perfectly! Thanks for adding this functionality in a very short time, awesome!

**Comment by aguirrel** [comment]
Great! Thanks to @nick-woodward he did it in a record time! :smile:
